peer:
  id: peer0
  networkId: dev
  listenAddress: 0.0.0.0:7051
  chaincodeListenAddress: 0.0.0.0:7052
  address: peer0.parentcompany.com:7051
  gossipBootstrap: peer0.parentcompany.com:7051
  localMspId: ParentCompanyMSP
  mspConfigPath: crypto-config/peerOrganizations/parentcompany.com/peers/peer0.parentcompany.com/msp
  tlsCACerts:
    path: crypto-config/peerOrganizations/parentcompany.com/peers/peer0.parentcompany.com/tls/ca.crt
  client:
    connTimeout: 3s
  deliveryclient:
    reconnectTotalTimeThreshold: 3600s
  events:
    address: peer0.parentcompany.com:7053
    serverHostname: peer0.parentcompany.com
  tlsEnabled: true
  tlsClient:
    keyfile: crypto-config/peerOrganizations/parentcompany.com/peers/peer0.parentcompany.com/tls/server.key
    certfile: crypto-config/peerOrganizations/parentcompany.com/peers/peer0.parentcompany.com/tls/server.crt
    rootcertfile: crypto-config/peerOrganizations/parentcompany.com/peers/peer0.parentcompany.com/tls/ca.crt
  authentication:
    timewindow: 15m